// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKwKXp-cKEZEWGlB9JgAn1FPGbjT0oA0',
    appId: '1:118463185378:web:634fdda2db8c0da0a639bb',
    messagingSenderId: '118463185378',
    projectId: 'my-notes-001',
    authDomain: 'my-notes-001.firebaseapp.com',
    storageBucket: 'my-notes-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphlQlsQzI5W8TNg5CplMioS_cYBFUlSo',
    appId: '1:118463185378:android:efe4e5e61b3a5595a639bb',
    messagingSenderId: '118463185378',
    projectId: 'my-notes-001',
    storageBucket: 'my-notes-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcjDjz3x3EyzHh-8STBCA24yK3NeTPf0',
    appId: '1:118463185378:ios:c779ef6d777e8fd5a639bb',
    messagingSenderId: '118463185378',
    projectId: 'my-notes-001',
    storageBucket: 'my-notes-001.appspot.com',
    iosClientId: '118463185378-4p890d4u88e4v8qdsqj8i7asjp0duls9.apps.googleusercontent.com',
    iosBundleId: 'mynotes',
  );
}
